version: 2.1
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
